### ISSUE TITLE
Intellij 11.1

### ISSUE THREAD

**Issue by fatlazycat** [derkork/intellij-leiningen-plugin#10]
Are you likely to release a compatible version ?

Thanks

**Comment by derkork** [comment]
Hi,

I'll have a look at it tonight. Unless they changed the API this should be matter of an hour or so. 

Jan

**Comment by derkork** [comment]
Leiningen 0.2.3 is now available and compatible with IDEA 11.1. Have fun with it :)

**Comment by fatlazycat** [comment]
Thanks !
