### ISSUE TITLE
lein medje and lein cucumber

### ISSUE THREAD

**Issue by uberto** [derkork/intellij-leiningen-plugin#12]
I'm learning clojure in a TDD fashion and I'd like to have these two commands on the list from intellij menu.

This is my project.clj

(defproject iad/iad "0.1" 
  :dependencies [[org.clojure/clojure "1.4.0"]
                 [ring "1.1.1"]
                 [ring-json-params "0.1.3"]
                 [clj-json "0.5.1"]
                 [compojure "1.1.1"]]
  :profiles {:dev {:dependencies [[midje "1.4.0"]
                                  [clj-http "0.5.0"]]}}
  :main iad.core
  :min-lein-version "2.0.0"
  :plugins [[lein-midje "2.0.0-SNAPSHOT"]
            [lein-cucumber "1.0.0"]]
  :cucumber-feature-paths ["test/features/"]
  :repositories {"ibiblio" "http://mirrors.ibiblio.org/pub/mirrors/maven2/"
                "clojars.org" "http://clojars.org/repo"}
  :description "IAD Conference Rest Server")

**Comment by derkork** [comment]
I see. I'm going to add support for leiningen plugins (if the api allows for this). In the meantime, you can launch leiningen with unavailable commands using a run configuration.  In IntelliJ's main menu select "Run" -> "Edit Configurations". Then press the little plus icon in the upper left corner of the dialog and select "Leiningen". This will create a new leiningen run configuration. You can specify arbitrary arguments to leiningen in this and then simply run this configuration from the run menu (just like you would run a debug session).

**Comment by uberto** [comment]
Thanks!
Btw I don't have much time but if I can help with the plugin dev, just let
me know.

cheers

Uberto

**Comment by fatlazycat** [comment]
Hi, any update ? Would be great to have autotest with midje.

**Comment by derkork** [comment]
This project is no longer actively maintained by me. If you’re looking for a Clojure development environment based
on IntelliJ and with Leiningen support, check out Cursive . If you want to add new
functionality to this plugin, feel free to fork and modify it as you like.
