### ISSUE TITLE
not working with intellij 12

### ISSUE THREAD

**Issue by ghost** [derkork/intellij-leiningen-plugin#13]
The plugin is not working correctly with the new intellij ide 12. Every time the IDE is restarted all projects are gone from the plugin window and have to be manually added. Also trying to run any command returns the following error: 
NoSuchMethodError: com.intellij.execution.RunManagerEx.createConfiguration(Ljava/lang/String;Lcom/intellij/execution/configurations/ConfigurationFactory;)Lcom/intellij/execution/impl/RunnerAndConfigurationSettingsImpl;: com.intellij.execution.RunManagerEx.createConfiguration(Ljava/lang/String;Lcom/intellij/execution/configurations/ConfigurationFactory;)Lcom/intellij/execution/impl/RunnerAndConfigurationSettingsImpl;

**Comment by derkork** [comment]
The API has probably changed and I have not yet updated the plug-in for IDEA 12. How did you actually manage to install it? It should not show up on the plugin list.

**Comment by wolverian** [comment]
The plugin is visible in IntelliJ IDEA 12 EAP's plugins list. I don't know why.

**Comment by 256BitChris** [comment]
Jan, 
    Are you going to be looking at this soon?  If not, I can take a look at it and see what's wrong - but do we want to create a branch for 11 before we do anything?

**Comment by derkork** [comment]
i added an IDEA 11 branch (named 'idea11'). I suggest we continue to work on master for IDEA12 and backport fixes to the IDEA 11 branch if necessary. If you have the time, feel free to look into this :)

**Comment by 256BitChris** [comment]
Pull Request #17 contains the necessary fixes to support IntelliJ 12.0.

**Comment by derkork** [comment]
Merged pull request and currently uploading new version to the plugin repo.
