### ISSUE TITLE
java source path not included in IDEA sources

### ISSUE THREAD

**Issue by viacoban** [derkork/intellij-leiningen-plugin#19]
project.clj has a separate java source path through:
:java-source-paths["src/main/java"]

when leiningen plugin refreshes idea project it does not include java source as module source

plugin version 0.3.0

**Comment by 256BitChris** [comment]
Thanks for reporting this and I apologize for the oversight.  I've added Pull Request #21 which addresses this issue.

**Comment by derkork** [comment]
Uploaded new versions 0.3.1 / 0.2.5 with fixes for #19 and #20 to the plugin repo.
