### ISSUE TITLE
Intellij 126+ uses 0.0.3

### ISSUE THREAD

**Issue by scottbessler** [derkork/intellij-leiningen-plugin#26]
Due to the max compatible version on the latest version of the plugin, the latest versions of IntelliJ 12 use an ancient 0.0.3 version that does not work properly.

**Comment by iNikem** [comment]
Confirm and vote for this issue.

**Comment by aadrian** [comment]
No wonder that many don't know about this plug-in since in the IntelliJ plug-in browser appears only the the ancient version (0.0.3 is from 2010).

One more reason to merge this plug-in with the LaClojure one. See: https://github.com/derkork/intellij-leiningen-plugin/issues/29

**Comment by derkork** [comment]
Duplicate of #30
