### ISSUE TITLE
Project output path reset on leiningen project refresh

### ISSUE THREAD

**Issue by netvl** [derkork/intellij-leiningen-plugin#3]
When leiningen project refresh is triggered (either when idea project is opened or when "refresh" button in leiningen tool window clicked), the current module output path and test output path drop to something like '/project/module/classes', which seems to me as completely random name - my project.clj specifies that the target directory is "out" and classes directory is "out/classes".
I think that project output dir should either left alone or set to the directory specified in the project.clj file.

**Comment by netvl** [comment]
I decided to start working on this issue in my fork. Should be decent experience :) I also noticed that plugin is not evaluating project.clj in right way (using Clojure), so I'm fixing this too.

**Comment by derkork** [comment]
Thanks for filing a patch. I just pulled your changes, added a minor fix and a few tweaks to the documentation and uploaded it as 0.2.0 to the plugin repository.
