### ISSUE TITLE
org.intellij.clojure?

### ISSUE THREAD

**Issue by Quasaur** [derkork/intellij-leiningen-plugin#42]
I downloaded / installed the latest stable community edition (12.1.4) and then installed the plugin (0.3.4) from JetBrains.

When it installs it says it's looking for a dependency plugin: org.intellij.clojure.

I realized that org.intellij.clojure is La Clojure.

I tried both the 0.5.7 and the 0.7.36 versions and Intellij 12.1.4 says that their both incompatible with that version...do i need to go back to Intellij II?

I used IntelliJ's 12.1.4's built-in repository browser and installed 0.5.286 of La Clojure and 0.3.4 of the Leiningen plugin...it seems to be working now.

**Comment by derkork** [comment]
Yap, the plugin depends on LaClojure.
